apiVersion: v1
kind: Pod
metadata:
  name: mi3dor-hps-pod
spec:
  restartPolicy: Never
  containers:
  - name: mi3dor-hps-pod
    image: beuthdritter/synthnet-finetuning
    env:
    - name: WANDB_API_KEY
      valueFrom:
        secretKeyRef:
          name: wandb-secret
          key: secret
          optional: false
    volumeMounts:
            - name: synthnet-finetuning-volume
              mountPath: /workspace/data
            - name: output-volume
              mountPath: /workspace/out
    command:
      [
        "bash",
        "scripts/mi3dor_vit_hyperparameter_search.sh" ,
      ]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "32Gi"
        cpu: "32"
  nodeSelector:
    gpu: v100
  volumes:
  - name: synthnet-finetuning-volume 
    persistentVolumeClaim:
      claimName: synthnet-finetuning-pvc
  - name: output-volume 
    persistentVolumeClaim:
      claimName: output-pvc
