apiVersion: v1
kind: Pod
metadata:
  name: modelnet10-vit-da-augmix
spec:
  restartPolicy: Never
  containers:
  - name: synthnet_da
    image: beuthdritter/synthnet-finetuning
    env:
    - name: GIT_NAME
      valueFrom:
        secretKeyRef:
          name: git-creds
          key: username
          optional: false
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          name: git-creds
          key: token
          optional: false
    - name: WANDB_API_KEY
      valueFrom:
        secretKeyRef:
          name: wandb-secret
          key: secret
          optional: false
    volumeMounts:
            - name: synthnet-finetuning-volume
              mountPath: /workspace/data
            - name: output-volume
              mountPath: /workspace/out
            - name: src-volume
              mountPath: /src-pv
    command:
      [
        "/bin/bash",
        "-c",
      ]
    args:
      - cd /src-pv/feature-extractor-finetuning;
        git checkout develop;
        git pull;
        cd /workspace;
        cp -r /src-pv/feature-extractor-finetuning/* /workspace;
        bash scripts/modelnet10_vit_da.sh;
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "32Gi"
        cpu: "32"
  nodeSelector:
    gpu: a100
  volumes:
  - name: synthnet-finetuning-volume 
    persistentVolumeClaim:
      claimName: synthnet-finetuning-pvc
  - name: output-volume 
    persistentVolumeClaim:
      claimName: output-pvc
  - name: src-volume
    persistentVolumeClaim:
      claimName: src-pvc
