_target_: models.swinv2_cdan_module.SwinV2CDANModule

model_name: "microsoft/swinv2-base-patch4-window12-192-22k"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.1

scheduler:
  null
  # _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  # _partial_: true
  # T_max: ${trainer.max_epochs}
  # verbose: false
# scheduler:
#   _target_: torch.optim.lr_scheduler.LinearLR
#   _partial_: true
#   start_factor: 0.1
#   end_factor: 1.0
#   total_iters: 2
#   verbose: true
