apiVersion: v1
kind: Pod
metadata:
  name: stl-bgsynth-srconly
spec:
  restartPolicy: Never
  containers:
    - name: stl-bgsynth-srconly
      image: beuthdritter/synthnet-transfer-learning
      env:
        - name: GIT_NAME
          valueFrom:
            secretKeyRef:
              name: git-creds
              key: username
              optional: false
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-creds
              key: token
              optional: false
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-secret
              key: secret
              optional: false
      volumeMounts:
        - name: synthnet-finetuning-volume
          mountPath: /workspace/data
        - name: output-volume
          mountPath: /workspace/out
        - name: src-volume
          mountPath: /src-pv
        - name: dshm
          mountPath: /dev/shm
      command: ["/bin/bash", "-c"]
      args:
        # - while true; do sleep 30; done;
        - cd /src-pv/synthnet-transfer-learning;
          git checkout main;
          git pull;
          cd /workspace;
          cp -r /src-pv/synthnet-transfer-learning/* /workspace;
          python -u src/train.py -m 'experiment=
          swinv2_ch_sgd1e-3_train_canny_hand_20steps_032cncs_175gui_07sci.yaml,
          swinv2_ch_sgd1e-3_train_wood_20steps_default.yaml,
          swinv2_ch_sgd1e-3_train_wood_canny_7s_066-084cncs_75gui.yaml,
          swinv2_ch_sgd1e-3_train_wood_canny_7s_066cncs_75gui.yaml,
          swinv2_ch_sgd1e-3_train_wood_canny_7s_066cncs_75gui_RS.yaml,
          swinv2_ch_sgd1e-3_train_wood_canny_7s_066cncs_75gui_hand.yaml,
          swinv2_ch_sgd1e-3_train_wood_depth_7s_084cncs_75gui.yaml,
          swinv2_ch_sgd1e-3_train_wood_depth_7s_084cncs_75gui_hand.yaml,
          vitb16_ch_sgd1e-3_train_canny_hand_20steps_032cncs_175gui_07sci.yaml,
          vitb16_ch_sgd1e-3_train_wood_20steps_default.yaml,
          vitb16_ch_sgd1e-3_train_wood_canny_7s_066-084cncs_75gui.yaml,
          vitb16_ch_sgd1e-3_train_wood_canny_7s_066cncs_75gui.yaml,
          vitb16_ch_sgd1e-3_train_wood_canny_7s_066cncs_75gui_RS.yaml,
          vitb16_ch_sgd1e-3_train_wood_canny_7s_066cncs_75gui_hand.yaml,
          vitb16_ch_sgd1e-3_train_wood_depth_7s_084cncs_75gui.yaml,
          vitb16_ch_sgd1e-3_train_wood_depth_7s_084cncs_75gui_hand.yaml'
      resources:
        limits:
          nvidia.com/gpu: 1
          # memory: 64
          # cpu: 16
  nodeSelector:
    gpu: v100
  volumes:
    - name: synthnet-finetuning-volume
      persistentVolumeClaim:
        claimName: synthnet-finetuning-pvc
    - name: output-volume
      persistentVolumeClaim:
        claimName: output-pvc
    - name: src-volume
      persistentVolumeClaim:
        claimName: src-pvc
    - name: dshm
      emptyDir:
        medium: Memory
