apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: beuthdritter/synthnet-transfer-learning
      env:
        - name: GIT_NAME
          valueFrom:
            secretKeyRef:
              name: git-creds
              key: username
              optional: false
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-creds
              key: token
              optional: false
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-secret
              key: secret
              optional: false
      volumeMounts:
        - name: synthnet-finetuning-volume
          mountPath: /workspace/data
        - name: output-volume
          mountPath: /workspace/out
        - name: src-volume
          mountPath: /src-pv
      command: ["/bin/bash", "-c"]
      args:
        # - while true; do sleep 30; done;
        - cd /src-pv/synthnet-transfer-learning
          git checkout main;
          git pull;
          cd /workspace;
          cp -r /src-pv/synthnet-transfer-learning/* /workspace;
          python src/train.py --config-dir configs --config-name train.yaml experiment=toy/visda2017/toy_vitb16_ch5;
      resources:
        limits:
          nvidia.com/gpu: 1
          memory: "32Gi"
          cpu: "32"
  nodeSelector:
    gpu: v100
  volumes:
    - name: synthnet-finetuning-volume
      persistentVolumeClaim:
        claimName: synthnet-finetuning-pvc
    - name: output-volume
      persistentVolumeClaim:
        claimName: output-pvc
    - name: src-volume
      persistentVolumeClaim:
        claimName: src-pvc
